export const PRELOADED_ICONS = [
  { name: "LeBron James", url: "/avatars/lebron.jpg" },
  { name: "Serena Williams", url: "/avatars/serena.jpg" },
  { name: "Lionel Messi", url: "/avatars/messi.jpg" },
  { name: "Tom Brady", url: "/avatars/brady.jpg" },
  { name: "Michael Jordan", url: "/avatars/michael.jpg" },
  { name: "Beyoncé", url: "/avatars/beyonce.jpg" },
  { name: "Drake", url: "/avatars/drake.jpg" },
  { name: "Bad Bunny", url: "/avatars/bad.jpg" },
  { name: "Taylor Swift", url: "/avatars/taylor.jpg" },
  { name: "Eminem", url: "/avatars/eminem.jpg" },
  { name: "Tom Hanks", url: "/avatars/tom.jpg" },
  { name: "Zendaya", url: "/avatars/zendaya.jpg" },
  { name: "The Rock", url: "/avatars/therock.jpg" },
  { name: "Scarlett Johansson", url: "/avatars/scarlett.jpg" },
  { name: "Mario", url: "/avatars/mario.jpg" },
  { name: "Lara Croft", url: "/avatars/lara.jpg" },
  { name: "Master Chief", url: "/avatars/master.jpg" },
  { name: "Pikachu", url: "/avatars/pikachu.jpg" },
  { name: "Link", url: "/avatars/link.jpg" },
  { name: "Kratos", url: "/avatars/kratos.jpg" }
];
